apiVersion: v1
kind: ConfigMap
metadata:
  name: node-operation-validator-config
  labels:
    {{- include "node-operation-validator.labels" . | nindent 4 }}
data:
  forbiddenUsers: {{ join "," .Values.config.forbiddenUsers | quote }}
  allowedReasons: {{join "," .Values.config.allowedReasons | quote}}
  reasonRegexPattern: {{ .Values.config.reasonRegexPattern | quote }}